stages:   
  - build
  - test
  - deploy

image: python:alpine

build site:
  stage: build
  script:
  - pip install mkdocs mkdocs-material pymdown-extensions
  - mkdocs build
  - mv site public
  artifacts:     
    expire_in: 1 day
    paths:
    - public

test site:
  stage: test
  script:
    - echo fake result as a placeholder

deploy dev:
  image: garland/docker-s3cmd
  stage: deploy
  environment: production
  except:
  - master
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - s3cmd --no-mime-magic --access_key=$ACCESS_KEY --secret_key=$SECRET_KEY --acl-public --delete-removed --delete-after --no-ssl --host=$S3HOST --host-bucket='$S3HOSTBUCKET' sync public s3://geeks-cookbook-dev

deploy prod:
  image: garland/docker-s3cmd
  stage: deploy
  environment: production
  only:
  - master
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - s3cmd --no-mime-magic --access_key=$ACCESS_KEY --secret_key=$SECRET_KEY --acl-public --delete-removed --delete-after --no-ssl --host=$S3HOST --host-bucket='$S3HOSTBUCKET' sync public s3://geeks-cookbook
