site_name: Funky Penguin's Geek Cookbook
site_description: 'The Geek Cookbook is a collection of guides for establishing your own highly-available docker container cluster (swarm). This swarm enables you to run self-hosted services such as GitLab, Plex, NextCloud, etc.'
site_author: 'David Young'
site_url: 'https://geek-cookbook.funkypenguin.co.nz'
edit_uri: 'edit/master/manuscript/'

# Fail to build if we have broken links
# strict: true

# Repository
repo_name: 'geek-cookbook'
repo_url: 'https://github.com/geek-cookbook/geek-cookbook'

# Set this to "manuscript" so that we can produce leanpub content
docs_dir: 'manuscript'

# Copyright
copyright: 'Copyright &copy; 2016 - 2021 David Young, Funky Penguin Limited'

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - autolinks
  - macros:
      verbose: true



  # - htmlproofer

#theme_dir: mkdocs-material
nav:
    - Home: index.md         
    - Docker Swarm: 
      - Preparation:
        - Design: ha-docker-swarm/design.md
        - Nodes: ha-docker-swarm/nodes.md
        - Shared Storage (Ceph): ha-docker-swarm/shared-storage-ceph.md
        - Shared Storage (GlusterFS): ha-docker-swarm/shared-storage-gluster.md
        - Keepalived: ha-docker-swarm/keepalived.md
        - Docker Swarm Mode: ha-docker-swarm/docker-swarm-mode.md
        - Traefik: ha-docker-swarm/traefik.md
        - Traefik Forward Auth: 
            - Start: ha-docker-swarm/traefik-forward-auth.md 
            - Google: ha-docker-swarm/traefik-forward-auth/google.md      
            - KeyCloak: ha-docker-swarm/traefik-forward-auth/keycloak.md
        - Registry: ha-docker-swarm/registry.md
        - Mail Server: recipes/mail.md
        - Duplicity: recipes/duplicity.md
      - Chef's Favorites:
        - Auto Pirate:
          - Start: recipes/autopirate.md
          - SABnzbd: recipes/autopirate/sabnzbd.md
          - NZBGet: recipes/autopirate/nzbget.md
          - Rtorrent: recipes/autopirate/rtorrent.md
          - Sonarr: recipes/autopirate/sonarr.md
          - Radarr: recipes/autopirate/radarr.md
          - Mylar: recipes/autopirate/mylar.md
          - Lazy Librarian: recipes/autopirate/lazylibrarian.md
          - Headphones: recipes/autopirate/headphones.md
          - Lidarr: recipes/autopirate/lidarr.md
          - NZBHydra: recipes/autopirate/nzbhydra.md
          - Ombi: recipes/autopirate/ombi.md
          - Jackett: recipes/autopirate/jackett.md
          - Heimdall: recipes/autopirate/heimdall.md
          - End: recipes/autopirate/end.md
        - Emby: recipes/emby.md
        - Home Assistant:
          - Start: recipes/homeassistant.md
          - iBeacon: recipes/homeassistant/ibeacon.md
        - Huginn: recipes/huginn.md
        - Jellyfin: recipes/jellyfin.md
        - Kanboard: recipes/kanboard.md
        - KeyCloak: 
          - Start: recipes/keycloak.md      
          - Users: recipes/keycloak/create-user.md
          - OIDC Provider: recipes/keycloak/setup-oidc-provider.md        
          - OpenLDAP: recipes/keycloak/authenticate-against-openldap.md
        - Miniflux: recipes/miniflux.md
        - Munin: recipes/munin.md
        - NextCloud: recipes/nextcloud.md
        - phpIPAM: recipes/phpipam.md
        - Plex: recipes/plex.md
        - Portainer: recipes/portainer.md        
        - PrivateBin: recipes/privatebin.md
        - Restic: recipes/restic.md          
        - Swarmprom: recipes/swarmprom.md    
      - Recipes:
        - Bitwarden: recipes/bitwarden.md
        - Bookstack: recipes/bookstack.md
        - Calibre-Web: recipes/calibre-web.md
        - Collabora Online: recipes/collabora-online.md
        - CyberChef: recipes/cyberchef.md
        - Duplicati: recipes/duplicati.md
        - ElkarBackup: recipes/elkarbackup.md
        - Funkwhale: recipes/funkwhale.md
        - Ghost: recipes/ghost.md
        - GitLab: recipes/gitlab.md
        - GitLab Runner: recipes/gitlab-runner.md
        - Gollum: recipes/gollum.md
        - InstaPy: recipes/instapy.md
        - KeyCloak: 
          - Start: recipes/keycloak.md      
          - Users: recipes/keycloak/create-user.md
          - OIDC Provider: recipes/keycloak/setup-oidc-provider.md        
          - OpenLDAP: recipes/keycloak/authenticate-against-openldap.md      
        - Komga: recipes/komga.md
        - Linx: recipes/linx.md
        - Minio: recipes/minio.md
        - OpenLDAP: recipes/openldap.md
        - OwnTracks: recipes/owntracks.md
        - Photoprism: recipes/photoprism.md
        - Portainer: recipes/portainer.md        
        - Realms: recipes/realms.md
        - Restic: recipes/restic.md        
        - Tiny Tiny RSS: recipes/tiny-tiny-rss.md
        - Traefik: ha-docker-swarm/traefik.md
        - Traefik Forward Auth: 
            - Start: ha-docker-swarm/traefik-forward-auth.md      
            - KeyCloak: ha-docker-swarm/traefik-forward-auth/keycloak.md
        - Wallabag: recipes/wallabag.md
        - Wekan: recipes/wekan.md
        - Wetty: recipes/wetty.md       
      - Reference:
        - OAuth Proxy: reference/oauth_proxy.md
        - Data Layout: reference/data_layout.md
        - Networks: reference/networks.md
        - Containers: reference/containers.md
        - git-docker : reference/git-docker.md
        - OpenVPN : reference/openvpn.md
        - Troubleshooting: reference/troubleshooting.md         
      - Work-in-Progress:
  #       - MatterMost: recipes/mattermost.md
        - IPFS Cluster: recipes/ipfs-cluster.md
        - MQTT: recipes/mqtt.md
  #       - HackMD: recipes/hackmd.md
  #       - Mastodon: recipes/mastodon.md
  #       - Mayan EDMS: recipes/mayan-edms.md
  #       - Shaarli: recipes/shaarli.md
  #       - UniFi Controller: recipes/unifi-controller.md
  #       - CyberChef : recipes/cyberchef.md
    - Kubernetes:
      - Preparation:
        - Start: kubernetes/index.md
        - Design: kubernetes/design.md
        - Cluster: kubernetes/cluster.md
        - DIY Cluster: kubernetes/diycluster.md
        - Load Balancer: kubernetes/loadbalancer.md
        - Snapshots: kubernetes/snapshots.md
        - Helm: kubernetes/helm.md
        - Traefik: kubernetes/traefik.md      
      - Chef's Favorites:
        - Kanboard: recipes/kubernetes/kanboard.md
        - Miniflux: recipes/kubernetes/miniflux.md
    - ðŸš€ Get Premix!:
      - Start: premix.md
      - Ansible: 
        - Operation: premix/ansible/operation.md        
        - Design: premix/ansible/design.md
      - Swarm: premix/swarm.md
      - Kubernetes: premix/kubernetes.md      
    - CHANGELOG: CHANGELOG.md
    - Support: support.md      
    - Contribute: community/contribute.md
    - Community: 
      - Discord: community/discord.md 
      - Support: support.md      
      - Contribute: community/contribute.md
      - Code of Conduct: community/code-of-conduct.md 
 
    #   # - Discourse: community/discourse.md
    #   # - GitHub: community/github.md    

theme:
  name: 'material'
  custom_dir: 'overrides'
  # disqus: 'geeks-cookbook'
  logo: 'images/site-logo.svg'
  favicon: 'images/site-logo.svg'
  features:
      - navigation.tabs
      - navigation.instant 
      - navigation.tabs.sticky  
      - navigation.sections
      - search.suggest
#      - search.highlight
      - search.share
  icon:
    repo: 'fontawesome/brands/github'
  palette:
    # Toggle light mode
    - scheme: default
      primary: 'black'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch
        name: Burn my eyes!

    # Toggle dark mode
    - scheme: slate
      primary: 'grey'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Love my eyes!

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/funkypenguin'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/funkypenguin'
    - icon: 'fontawesome/brands/stack-overflow'
      link: 'https://stackoverflow.com/cv/funkypenguin'
    - icon: 'material/rss'
      link: 'https://www.funkypenguin.co.nz/'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/funkypenguin'
    - icon: 'material/library'
      link: 'https://leanpub.com/geeks-cookbook'    
    - icon: 'material/mailbox'
      link: 'mailto:davidy@funkypenguin.co.nz?Subject=Hello%2C%20from%20a%20geek-cookbook%20reader%20%3B%29'             
  generator: false  

# Google Analytics
google_analytics:
  - 'UA-139253-18'
  - 'auto'

# extra_css:

extra_javascript:
  - extras/javascript/discord.js
  - extras/javascript/sortable-tables.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path: _snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg    
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: funkypenguin
      repo: geek-cookbook  
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed  
  - meta
