site_name: Funky Penguin's Geek Cookbook
site_description: 'The "Geek Cookbook" is a collection of guides for establishing your own highly-available docker container cluster (swarm). This swarm enables you to run self-hosted services such as GitLab, Plex, NextCloud, etc.'
site_author: 'David Young'
site_url: 'https://geek-cookbook.funkypenguin.co.nz'
edit_uri: 'edit/master/manuscript/'

# Fail to build if we have broken links
strict: true

# Repository
repo_name: 'geek-cookbook/yes-this-is-it'
repo_url: 'https://github.com/geek-cookbook/yes-this-is-it'

# Set this to "manuscript" so that we can produce leanpub content
docs_dir: 'manuscript'

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 David Young, Funky Penguin Limited'

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  # this doesn't work with the current netlify build process, which modifies .md files in the "publish" subfolder before building
  # - git-revision-date-localized:
  #     type: date
  - autolinks
  # - htmlproofer

#theme_dir: mkdocs-material
nav:
    - Home: 
      - What is this: index.md
      - About: whoami.md
      - Sponsored Projects: sponsored-projects.md 
    # - 'Join Us! ü§ù':
    #   - Hello: recipes/general/start.md
    #   - iPad Pro Geeking: recipes/general/ipad-pro-geeking.md
    #   - Kid-safe WiFi: recipes/general/kid-safe-wifi.md      
    # Upcoming section
    # - '#geeklife':
    #   - Hello: recipes/general/start.md
    #   - iPad Pro Geeking: recipes/general/ipad-pro-geeking.md
    #   - Kid-safe WiFi: recipes/general/kid-safe-wifi.md              
    - Docker Swarm: 
      - Preparation:
        - Design: ha-docker-swarm/design.md
        - Nodes: ha-docker-swarm/nodes.md
        - Shared Storage (Ceph): ha-docker-swarm/shared-storage-ceph.md
        - Shared Storage (GlusterFS): ha-docker-swarm/shared-storage-gluster.md
        - Keepalived: ha-docker-swarm/keepalived.md
        - Docker Swarm Mode: ha-docker-swarm/docker-swarm-mode.md
        - Traefik: ha-docker-swarm/traefik.md
        - Traefik Forward Auth: 
            - Start: ha-docker-swarm/traefik-forward-auth.md      
            - KeyCloak: ha-docker-swarm/traefik-forward-auth/keycloak.md
        - Registry: ha-docker-swarm/registry.md
        - Mail Server: recipes/mail.md
        - Duplicity: recipes/duplicity.md
      - Chef's Favorites:
        - Auto Pirate:
          - Start: recipes/autopirate.md
          - SABnzbd: recipes/autopirate/sabnzbd.md
          - NZBGet: recipes/autopirate/nzbget.md
          - Rtorrent: recipes/autopirate/rtorrent.md
          - Sonarr: recipes/autopirate/sonarr.md
          - Radarr: recipes/autopirate/radarr.md
          - Mylar: recipes/autopirate/mylar.md
          - Lazy Librarian: recipes/autopirate/lazylibrarian.md
          - Headphones: recipes/autopirate/headphones.md
          - Lidarr: recipes/autopirate/lidarr.md
          - NZBHydra: recipes/autopirate/nzbhydra.md
          - NZBHydra 2: recipes/autopirate/nzbhydra2.md
          - Ombi: recipes/autopirate/ombi.md
          - Jackett: recipes/autopirate/jackett.md
          - Heimdall: recipes/autopirate/heimdall.md
          - End: recipes/autopirate/end.md
        - ElkarBackup: recipes/elkarbackup.md
        - Emby: recipes/emby.md
        - Home Assistant:
          - Start: recipes/homeassistant.md
          - iBeacon: recipes/homeassistant/ibeacon.md
        - Huginn: recipes/huginn.md
        - Kanboard: recipes/kanboard.md
        - KeyCloak: 
          - Start: recipes/keycloak.md      
          - Users: recipes/keycloak/create-user.md
          - OIDC Provider: recipes/keycloak/setup-oidc-provider.md        
          - OpenLDAP: recipes/keycloak/authenticate-against-openldap.md
        - Miniflux: recipes/miniflux.md
        - Munin: recipes/munin.md
        - NextCloud: recipes/nextcloud.md
        - OwnTracks: recipes/owntracks.md
        - phpIPAM: recipes/phpipam.md
        - Plex: recipes/plex.md
        - PrivateBin: recipes/privatebin.md
        - Swarmprom: recipes/swarmprom.md    
      - Recipes:
        - Bitwarden: recipes/bitwarden.md
        - Bookstack: recipes/bookstack.md
        - Calibre-Web: recipes/calibre-web.md
        - Collabora Online: recipes/collabora-online.md
        - Ghost: recipes/ghost.md
        - GitLab: recipes/gitlab.md
        - GitLab Runner: recipes/gitlab-runner.md
        - Gollum: recipes/gollum.md
        - InstaPy: recipes/instapy.md
        - KeyCloak: 
          - Start: recipes/keycloak.md      
          - Users: recipes/keycloak/create-user.md
          - OIDC Provider: recipes/keycloak/setup-oidc-provider.md        
          - OpenLDAP: recipes/keycloak/authenticate-against-openldap.md      
        - Minio: recipes/minio.md
        - OpenLDAP: recipes/openldap.md
        - Piwik: recipes/piwik.md
        - Portainer: recipes/portainer.md
        - Realms: recipes/realms.md
        - Tiny Tiny RSS: recipes/tiny-tiny-rss.md
        - Traefik: ha-docker-swarm/traefik.md
        - Traefik Forward Auth: 
            - Start: ha-docker-swarm/traefik-forward-auth.md      
            - KeyCloak: ha-docker-swarm/traefik-forward-auth/keycloak.md
        - Wallabag: recipes/wallabag.md
        - Wekan: recipes/wekan.md
        - Wetty: recipes/wetty.md       
      - Reference:
        - OAuth Proxy: reference/oauth_proxy.md
        - Data Layout: reference/data_layout.md
        - Networks: reference/networks.md
        - Containers: reference/containers.md
        - git-docker : reference/git-docker.md
        - OpenVPN : reference/openvpn.md
        - Troubleshooting: reference/troubleshooting.md         
      - Work-in-Progress:
  #       - MatterMost: recipes/mattermost.md
        - IPFS Cluster: recipes/ipfs-cluster.md
        - MQTT: recipes/mqtt.md
  #       - HackMD: recipes/hackmd.md
  #       - Mastodon: recipes/mastodon.md
  #       - Mayan EDMS: recipes/mayan-edms.md
  #       - Shaarli: recipes/shaarli.md
  #       - UniFi Controller: recipes/unifi-controller.md
  #       - CyberChef : recipes/cyberchef.md
    - Kubernetes:
      - Preparation:
        - Start: kubernetes/start.md
        - Design: kubernetes/design.md
        - Cluster: kubernetes/cluster.md
        - DIY Cluster: kubernetes/diycluster.md
        - Load Balancer: kubernetes/loadbalancer.md
        - Snapshots: kubernetes/snapshots.md
        - Helm: kubernetes/helm.md
        - Traefik: kubernetes/traefik.md      
      - Chef's Favorites:
        - Kanboard: recipes/kubernetes/kanboard.md
     #   - Kubernetes Dashboard: recipes/kubernetes/kubernetes-dashboard.md
        - Miniflux: recipes/kubernetes/miniflux.md
  #      - NextCloud: recipes/kubernetes/nextcloud.md
  #      - phpIPAM: recipes/kubernetes/phpipam.md
  #      - PrivateBin: recipes/kubernetes/privatebin.md
    - CHANGELOG: 
      - CHANGELOG: CHANGELOG.md
    - Support: 
      - Support: support.md      

theme:
  name: 'material'
  custom_dir: 'overrides'
  disqus: 'geeks-cookbook'
  logo: 'images/site-logo.svg'
  favicon: 'images/site-logo.svg'
  features:
      - tabs
      - instant 
  icon:
    repo: 'fontawesome/brands/github'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/funkypenguin'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/funkypenguin'
    - icon: 'fontawesome/brands/stack-overflow'
      link: 'https://stackoverflow.com/cv/funkypenguin'
    - icon: 'material/rss'
      link: 'https://www.funkypenguin.co.nz/'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/funkypenguin'
    - icon: 'material/library'
      link: 'https://leanpub.com/geeks-cookbook'    
    - icon: 'material/mailbox'
      link: 'mailto:davidy@funkypenguin.co.nz?Subject=Hello%2C%20from%20a%20geek-cookbook%20reader%20%3B%29'             
  

# Google Analytics
google_analytics:
  - 'UA-139253-18'
  - 'auto'

extra_css:
  - 'stylesheets/mailchimp.css'

extra_javascript:
  - 'extras/javascript/discord.js'  

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg    
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: funkypenguin
      repo: geek-cookbook  
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed  
  - meta
