site_name: Funky Penguin's Geek Cookbook
site_description: 'The "Geek Cookbook" is a collection of guides for establishing your own highly-available docker container cluster (swarm). This swarm enables you to run self-hosted services such as GitLab, Plex, NextCloud, etc.'
site_author: 'David Young'
site_url: 'https://geek-cookbook.funkypenguin.co.nz'
edit_uri: 'edit/master/manuscript/'

# Fail to build if we have broken links
strict: true

# Repository
repo_name: 'funkypenguin/geek-cookbook'
repo_url: 'https://github.com/funkypenguin/geek-cookbook'

# Set this to "manuscript" so that we can produce leanpub content
docs_dir: 'manuscript'

# Copyright
copyright: 'Copyright &copy; 2016 - 2019 David Young'


#theme_dir: mkdocs-material
nav:
    - Home: index.md
    - Introduction:
      - README: README-UI.md
      - CHANGELOG: CHANGELOG.md
      - whoami: whoami.md
    - Docker Swarm:
      - Design: ha-docker-swarm/design.md
      - VMs: ha-docker-swarm/vms.md
      - Shared Storage (Ceph): ha-docker-swarm/shared-storage-ceph.md
      - Shared Storage (GlusterFS): ha-docker-swarm/shared-storage-gluster.md
      - Keepalived: ha-docker-swarm/keepalived.md
      - Docker Swarm Mode: ha-docker-swarm/docker-swarm-mode.md
      - Traefik: ha-docker-swarm/traefik.md
      - Traefik Forward Auth: ha-docker-swarm/traefik-forward-auth.md
      - Registry: ha-docker-swarm/registry.md
      - Mail Server: recipes/mail.md
      - Duplicity: recipes/duplicity.md
    - Kubernetes Cluster:
      - Start: kubernetes/start.md
      - Design: kubernetes/design.md
      - Cluster: kubernetes/cluster.md
      - Load Balancer: kubernetes/loadbalancer.md
      - Snapshots: kubernetes/snapshots.md
      - Helm: kubernetes/helm.md
      - Traefik: kubernetes/traefik.md      
    - Chef's Favorites (Docker):
      - Auto Pirate:
        - Start: recipes/autopirate.md
        - SABnzbd: recipes/autopirate/sabnzbd.md
        - NZBGet: recipes/autopirate/nzbget.md
        - Rtorrent: recipes/autopirate/rtorrent.md
        - Sonarr: recipes/autopirate/sonarr.md
        - Radarr: recipes/autopirate/radarr.md
        - Mylar: recipes/autopirate/mylar.md
        - Lazy Librarian: recipes/autopirate/lazylibrarian.md
        - Headphones: recipes/autopirate/headphones.md
        - Lidarr: recipes/autopirate/lidarr.md
        - NZBHydra: recipes/autopirate/nzbhydra.md
        - NZBHydra 2: recipes/autopirate/nzbhydra2.md
        - Ombi: recipes/autopirate/ombi.md
        - Jackett: recipes/autopirate/jackett.md
        - Heimdall: recipes/autopirate/heimdall.md
        - End: recipes/autopirate/end.md
      - ElkarBackup: recipes/elkarbackup.md
      - Emby: recipes/emby.md
      - Home Assistant:
        - Start: recipes/homeassistant.md
        - iBeacon: recipes/homeassistant/ibeacon.md
      - Huginn: recipes/huginn.md
      - Kanboard: recipes/kanboard.md
      - KeyCloak: recipes/keycloak.md      
      - Miniflux: recipes/miniflux.md
      - Munin: recipes/munin.md
      - NextCloud: recipes/nextcloud.md
      - OwnTracks: recipes/owntracks.md
      - phpIPAM: recipes/phpipam.md
      - Plex: recipes/plex.md
      - PrivateBin: recipes/privatebin.md
      - Swarmprom: recipes/swarmprom.md
      - Turtle Pool: recipes/turtle-pool.md
    - Chef's Favorites (Kubernetes):
      - Kanboard: recipes/kubernetes/kanboard.md
      - Miniflux: recipes/kubernetes/miniflux.md
#      - NextCloud: recipes/kubernetes/nextcloud.md
#      - phpIPAM: recipes/kubernetes/phpipam.md
#      - PrivateBin: recipes/kubernetes/privatebin.md
    - Menu:
      - Bitwarden: recipes/bitwarden.md
      - Bookstack: recipes/bookstack.md
      - CryptoMiner:
        - Start: recipes/cryptominer.md
        - Mining Rig: recipes/cryptominer/mining-rig.md
        - AMD GPU: recipes/cryptominer/amd-gpu.md
        - NVidia GPU: recipes/cryptominer/nvidia-gpu.md
        - Mining Pools : recipes/cryptominer/mining-pool.md
        - Wallets : recipes/cryptominer/wallet.md
        - Exchanges: recipes/cryptominer/exchange.md
        - Minerhotel: recipes/cryptominer/minerhotel.md
        - Monitoring: recipes/cryptominer/monitor.md
        - Profit!: recipes/cryptominer/profit.md
      - Calibre-Web: recipes/calibre-web.md
      - Collabora Online: recipes/collabora-online.md
      - Ghost: recipes/ghost.md
      - GitLab: recipes/gitlab.md
      - GitLab Runner: recipes/gitlab-runner.md
      - Gollum: recipes/gollum.md
      - InstaPy: recipes/instapy.md
      - Minio: recipes/minio.md
      - OpenLDAP: recipes/openldap.md
      - Piwik: recipes/piwik.md
      - Portainer: recipes/portainer.md
      - Realms: recipes/realms.md
      - Tiny Tiny RSS: recipes/tiny-tiny-rss.md
      - Wallabag: recipes/wallabag.md
      - Wekan: recipes/wekan.md
      - Wetty: recipes/wetty.md
    - Work-in-Progress:
#       - MatterMost: recipes/mattermost.md
       - IPFS Cluster: recipes/ipfs-cluster.md
       - MQTT: recipes/mqtt.md
#       - HackMD: recipes/hackmd.md
#       - Mastodon: recipes/mastodon.md
#       - Mayan EDMS: recipes/mayan-edms.md
#       - Shaarli: recipes/shaarli.md
#       - UniFi Controller: recipes/unifi-controller.md
#       - CyberChef : recipes/cyberchef.md
    - Reference:
      - OAuth Proxy: reference/oauth_proxy.md
      - Data Layout: reference/data_layout.md
      - Networks: reference/networks.md
      - Containers: reference/containers.md
      - git-docker : reference/git-docker.md
      - OpenVPN : reference/openvpn.md
      - Troubleshooting: reference/troubleshooting.md
    - Support: support.md
    - Sponsored Projects: sponsored-projects.md

theme:
  name: 'material'
  custom_dir: 'overrides'
  disqus: 'geeks-cookbook'
  logo: 'images/site-logo.png'
  favicon: 'images/favicon.ico'
  feature:
    tabs: false
  palette:
    primary: 'brown'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/funkypenguin'
    - type: 'twitter'
      link: 'https://twitter.com/funkypenguin'
    - type: 'stack-overflow'
      link: 'https://stackoverflow.com/cv/funkypenguin'
    - type: 'rss'
      link: 'https://www.funkypenguin.co.nz/blog/'
    - type: 'envelope'
      link: 'mailto:davidy@funkypenguin.co.nz?Subject=Hello%2C%20from%20a%20geek-cookbook%20reader%20%3B%29'
    - type: 'book'
      link: 'https://leanpub.com/geeks-cookbook'

# Google Analytics
google_analytics:
  - 'UA-139253-18'
  - 'auto'

#extra_javascript:
# - 'extras/javascript/discord.js'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
