site_name: Funky Penguin's Geek's Cookbook
site_description: 'A short description of my project'
site_author: 'David Young'
site_url: 'https://geeks-cookbook.funkypenguin.co.nz'

# Repository
#repo_name: 'funkypenguin/geek-cookbook'
#repo_url: 'https://github.com/funkypenguin/geeks-cookbook'
# repo_url: 'https://gitlab.funkypenguin.co.nz/funkypenguin/geeks-cookbook'

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 David Young'


theme: material
theme_dir: mkdocs-material
pages:
    - Home : index.md
    - Introduction:
      - README: README.md
      - whoami: whoami.md
    - Essential:
      - Design: ha-docker-swarm/design.md
      - VMs: ha-docker-swarm/vms.md
      - Shared Storage (Ceph): ha-docker-swarm/shared-storage-ceph.md
      - Shared Storage (GlusterFS): ha-docker-swarm/shared-storage-gluster.md
      - Keepalived: ha-docker-swarm/keepalived.md
      - Docker Swarm Mode: ha-docker-swarm/docker-swarm-mode.md
      - Traefik: ha-docker-swarm/traefik.md
    - Recommended:
      - Mail Server: recipies/mail.md
      - GitLab: recipies/gitlab.md
#      - Basic: advanced/tiny-tiny-rss.md
#      - Plugins: advanced/tiny-tiny-rss.md
#      - Themes: advanced/tiny-tiny-rss.md

#        - Home Assistant:
#          - About: advanced/home-assistant/basic.md
#          - Basic: advanced/home-assistant/basic.md
#          - Grafana: advanced/home-assistant/grafana.md
#          - Limitless LED: advanced/home-assistant/limitless-led.md
#          - OwnTracks: advanced/home-assistant/limitless-led.md

#        - Home Assistant:

#          - About: advanced/home-assistant/basic.md
#          - Basic: advanced/home-assistant/basic.md
#          - Grafana: advanced/home-assistant/grafana.md
#          - Limitless LED: advanced/home-assistant/limitless-led.md
#          - OwnTracks: advanced/home-assistant/limitless-led.md

#        - Huginn: advanced/huginn.md
#        - Nextcloud: advanced/nextcloud.md
#        - OwnTracks: advanced/owntracks.md
#        - Shaarli: advanced/shaarli.md
#        - Wallabag: advanced/wallabag.md




extra:
  disqus: 'geeks-cookbook'
  logo: 'images/site-logo.png'
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/funkypenguin'
    - type: 'twitter'
      link: 'https://twitter.com/funkypenguin'

# Google Analytics
google_analytics:
  - 'UA-139253-18'
  - 'auto'

extra_javascript:
  - 'extras/javascript/piwik.js'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
