blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: http://chat.funkypenguin.co.nz/
    about: For real-time, short-lived help, from whichever geeks happen to be online
  - name: Discourse Forums
    url: https://forum.funkypenguin.co.nz/
    about: For asyncronous, long-lived discussions