name: Update leanpub branches

on:
  push:
    branches:
      - dev
    paths:
      - 'manuscript/*.md'
      - 'manuscript/**/*.md'
      - '.github/workflows/*'


jobs:
  update-leanpub:
    name: update-leanpub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout charts repo
      uses: actions/checkout@v2

    - name: Checkout latest leanpub-preview branch
      uses: actions/checkout@v2
      with:    
        repository: ${{ env.GITHUB_PAGES_REPO }}
        ref: leanpub-preview  
        path: leanpub-preview

    - name: Replace contents of leanpub-preview branch
      run: |
        rm -rf leanpub-preview/manuscript
        rm -rf leanpub-preview/scripts
        cp -rf manuscript leanpub-preview/
        cp -rf scripts leanpub-preview/
        cd leanpub-preview
        ./scripts/markdown-to-markua.sh
        git config --local --unset-all "http.https://github.com/.extraheader"
        git config --global user.email "autopenguin@funkypenguin.co.nz"
        git config --global user.name "AutoPenguin"        
        git add .
        git commit -m 'Update for leanpub preview'        

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: leanpub-preview
        branch: leanpub-preview